server:
  port: 8080

spring:
  application:
    name:
      fmtok8s-game-frontend-service
  web:
    resources:
      static-locations: "file:static/" #for dev file:./target/static/ for docker static/
  rsocket:
    server:
      transport: websocket
      mapping-path: /ws/

game:
  index-page-path: "file:static/index.html"
  leaderboard-uri: http://get-leaderboard.default.svc.cluster.local
  start-game-uri: http://start-game.default.svc.cluster.local
  start-level-uri: http://start-level.default.svc.cluster.local
  levels:
  - name: "start"
    functionName: ""
  - name: "Level 1"
    functionName: "level-1"
    componentName: "Level1"
  - name: "Level 2"
    functionName: "level-2"
    componentName: "Level2"
  - name: "Level 3"
    functionName: "level-3"
    componentName: "Level3"
  - name: "Level 4"
    functionName: "level-4"
    componentName: "Level4"
  - name: "end"
    functionName: ""
    componentName: "GameComplete"
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always

logging:
  level:
    reactor:
      netty: info
    org:
      springframework:
        cloud:
          gateway: info
    com:
      salaboy:
        conferences:
          site: info
