spring:
  application:
    name:
      fmtok8s-game-frontend-service
  web:
    resources:
      static-locations: "file:static/" #for dev file:./target/static/ for docker static/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
    com:
      salaboy:
        conferences:
          site: INFO
