server:
  port: 8080

spring:
  application:
    name:
      fmtok8s-game-frontend-service
  web:
    resources:
      static-locations: "file:static/" #for dev file:./target/static/ for docker static/
  rsocket:
    server:
      transport: websocket
      mapping-path: /ws/

game:
  index-page-path: "file:static/index.html"
  leaderboard-uri: http://get-leaderboard.default.svc.cluster.local
  start-game-uri: http://start-game.default.svc.cluster.local
  levels:
  - name: "Start"
    functionName: ""
  - name: "Question 1"
    functionName: "kubeconeu-question-1"
    componentName: "KubeconEULevel1"
  - name: "Question 2"
    functionName: "kubeconeu-question-2"
    componentName: "KubeconEULevel2"
  - name: "Question 3"
    functionName: "kubeconeu-question-3"
    componentName: "KubeconEULevel3"
  - name: "Question 4"
    functionName: "kubeconeu-question-4"
    componentName: "KubeconEULevel4"
  - name: "Question 5"
    functionName: "kubeconeu-question-5"
    componentName: "KubeconEULevel5"
  - name: "End"
    functionName: ""
    componentName: "GameComplete"
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always

logging:
  level:
    reactor:
      netty: info
    org:
      springframework:
        cloud:
          gateway: info
    com:
      salaboy:
        conferences:
          site: info
