server:
  port: 8080

spring:
  application:
    name:
      fmtok8s-game-frontend-service
  web:
    resources:
      static-locations: "file:static/" #for dev file:./target/static/ for docker static/
  rsocket:
    server:
      transport: websocket
      mapping-path: /ws/

game:
  index-page-path: "file:static/index.html"
  leaderboard-uri: http://get-leaderboard.default.svc.cluster.local
  start-game-uri: http://start-game.default.svc.cluster.local
  start-level-uri: http://start-level.default.svc.cluster.local
  levels-and-functions:
    "Start": ""
    "Level1": "level-1"
    "Level2": "level-2"
    "Level3": "level-3"
    "Level4": "level-4"
    "End": ""
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always

logging:
  level:
    reactor:
      netty: info
    org:
      springframework:
        cloud:
          gateway: info
    com:
      salaboy:
        conferences:
          site: info
