apiVersion: v1
kind: Service
metadata:
  name: game-frontend
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"frontend-backendconfig"}}'
spec:
  type: LoadBalancer #this is needed to expose the service, using ingress will not work for websockets
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: salaboy/fmtok8s-game-frontend:0.1.5
          env:
            - name: EXTERNAL_IP
              value: <EXTERNAL_IP from the Loadbalancer Service here>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
# This is needed for GKE to work and don't close the websocket connection
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: frontend-backendconfig
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800

